refresher:
  refreshInterval: 1 # File/submodule refresh interval in seconds
  fetchInterval: 180 # In seconds
notARepository: 'skip'
scrollHeight: 6 # How many lines are scrolled
gui:
  theme:
    lightTheme: false
    # activeBorderColor:
    #   - blue
    #   - bold
    # inactiveBorderColor:
      # - "#000000"
    # optionsTextColor:
    #   - blue
    # selectedLineBgColor:
      # - "#E4F9F4" # set to `default` to have no background colour
    # selectedRangeBgColor:
    #   - blue
    # cherryPickedCommitBgColor:
    #   - cyan
    # cherryPickedCommitFgColor:
    #   - blue
    # unstagedChangesColor:
    #   - red
