refresher:
  refreshInterval: 1 # File/submodule refresh interval in seconds
  fetchInterval: 180 # In seconds
notARepository: 'skip'
gui:
  scrollHeight: 15 # How many lines are scrolled
  mainPanelSplitMode: 'vertical'
  showFileTree: false
  showIcons: false
  windowSize: 'half'
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    selectedRangeBgColor:
      - magenta
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
